### ISSUE TITLE
Unable to trigger release if artifact not primary

### ISSUE THREAD

**Issue by jacobsmaki** [aquiladev/vsts-trigger#6]
Given a release R1 with artifacts A1 and A2 (primary) and default version latest and release R2 with artifact A1 (primary) and default version latest, attempting to trigger R2 from R1 results in an error.

>2017-02-15T17:58:08.4456576Z ##[section]Starting: Release trigger: R2
>2017-02-15T17:58:08.4812083Z ==============================================================================
>2017-02-15T17:58:08.4812083Z Task         : Release Trigger
>2017-02-15T17:58:08.4812083Z Description  : Trigger release pipeline
>2017-02-15T17:58:08.4812083Z Version      : 0.1.1
>2017-02-15T17:58:08.4812083Z Author       : Sergii Bomko
>2017-02-15T17:58:08.4812083Z Help         : [More Information](https://github.com/aquiladev/vsts-trigger)
>2017-02-15T17:58:08.4812083Z ==============================================================================
>2017-02-15T17:58:08.5092082Z Preparing task execution handler.
>2017-02-15T17:58:13.6362418Z Executing the powershell script: D:\a\_tasks\ReleaseTrigger_b2d2e081-c1e0-4daf-b444-c492a02e47f8\0.1.1\ReleaseTrigger.ps1
>2017-02-15T17:58:13.9282381Z ReleaseDefinitionName= R2
>2017-02-15T17:58:13.9282381Z 
>2017-02-15T17:58:13.9282381Z 
>2017-02-15T17:58:13.9292382Z TeamProject= TP
>2017-02-15T17:58:13.9292382Z 
>2017-02-15T17:58:13.9292382Z 
>2017-02-15T17:58:13.9832377Z TfsUri= https://XXXXXX.vsrm.visualstudio.com/
>2017-02-15T17:58:13.9832377Z 
>2017-02-15T17:58:13.9832377Z 
>2017-02-15T17:58:13.9852378Z BuildDefinitionId= 80
>2017-02-15T17:58:13.9852378Z 
>2017-02-15T17:58:13.9852378Z 
>2017-02-15T17:58:13.9852378Z BuildDefinitionName= A2
>2017-02-15T17:58:13.9852378Z 
>2017-02-15T17:58:13.9852378Z 
>2017-02-15T17:58:13.9862389Z BuildId= 5432
>2017-02-15T17:58:13.9862389Z 
>2017-02-15T17:58:13.9862389Z 
>2017-02-15T17:58:17.0583273Z url= https://XXXXXX.vsrm.visualstudio.com/TP/_apis/release/definitions?$expand=artifacts&api-version=3.0-preview.1
>2017-02-15T17:58:17.0583273Z 
>2017-02-15T17:58:17.0583273Z 
>2017-02-15T17:58:18.2956287Z Get artifacts versions
>2017-02-15T17:58:18.2956287Z 
>2017-02-15T17:58:18.2956287Z 
>2017-02-15T17:58:18.2966169Z url= https://XXXXXX.vsrm.visualstudio.com/TP/_apis/release/artifacts/versions?api-version=3.0-preview.1
>2017-02-15T17:58:18.2966169Z 
>2017-02-15T17:58:18.2966169Z 
>2017-02-15T17:58:18.4614583Z body= {
>2017-02-15T17:58:18.4614583Z     "sourceId":  "69fe2265-92a6-484c-8711-2aa10257a1bd:150",
>2017-02-15T17:58:18.4614583Z     "type":  "Build",
>2017-02-15T17:58:18.4614583Z     "alias":  "A1",
>2017-02-15T17:58:18.4614583Z     "definitionReference":  {
>2017-02-15T17:58:18.4614583Z                                 "artifactSourceDefinitionUrl":  {
>2017-02-15T17:58:18.4614583Z                                                                     "id":  "https://XXXXXX.visualstudio.com/_permalink/_build/index?collectionId=bbdf648e-bdd3-4c5d-8450-835c543bf225\u0026projectId=69fe2265-92a6-484c-8711-2aa10257a1bd\u0026definitionId=150",
>2017-02-15T17:58:18.4614583Z                                                                     "name":  ""
>2017-02-15T17:58:18.4614583Z                                                                 },
>2017-02-15T17:58:18.4614583Z                                 "defaultVersionType":  {
>2017-02-15T17:58:18.4614583Z                                                            "id":  "latestType",
>2017-02-15T17:58:18.4614583Z                                                            "name":  "Latest"
>2017-02-15T17:58:18.4614583Z                                                        },
>2017-02-15T17:58:18.4614583Z                                 "definition":  {
>2017-02-15T17:58:18.4614583Z                                                    "id":  "150",
>2017-02-15T17:58:18.4624591Z                                                    "name":  "A1"
>2017-02-15T17:58:18.4624591Z                                                },
>2017-02-15T17:58:18.4624591Z                                 "project":  {
>2017-02-15T17:58:18.4624591Z                                                 "id":  "69fe2265-92a6-484c-8711-2aa10257a1bd",
>2017-02-15T17:58:18.4624591Z                                                 "name":  "TP"
>2017-02-15T17:58:18.4624591Z                                             }
>2017-02-15T17:58:18.4624591Z                             },
>2017-02-15T17:58:18.4624591Z     "isPrimary":  true
>2017-02-15T17:58:18.4624591Z }
>2017-02-15T17:58:18.4624591Z 
>2017-02-15T17:58:18.4624591Z 
>2017-02-15T17:58:18.6114895Z ##[error]System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find artifact versions.
>2017-02-15T17:58:18.6114895Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
>2017-02-15T17:58:18.6114895Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
>2017-02-15T17:58:18.6114895Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
>2017-02-15T17:58:18.6114895Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
>2017-02-15T17:58:18.6114895Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
>2017-02-15T17:58:18.6114895Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
>2017-02-15T17:58:18.6254896Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.

**Comment by rokeno** [comment]
We have encountered the same issue. No updates?
