### ISSUE TITLE
Unable to trigger release with multiple artifacts

### ISSUE THREAD

**Issue by jacobsmaki** [aquiladev/vsts-trigger#7]
Given a release R1 with artifacts A1 (primary) and A2 with default version latest and release R2 with artifacts A1 (primary) and A2 with default version latest, attempting to trigger a release results in an error.

>2017-02-15T18:09:31.7786422Z ##[section]Starting: Release trigger: R2
>2017-02-15T18:09:31.8089402Z ==============================================================================
>2017-02-15T18:09:31.8089402Z Task         : Release Trigger
>2017-02-15T18:09:31.8089402Z Description  : Trigger release pipeline
>2017-02-15T18:09:31.8089402Z Version      : 0.1.1
>2017-02-15T18:09:31.8089402Z Author       : Sergii Bomko
>2017-02-15T18:09:31.8089402Z Help         : [More Information](https://github.com/aquiladev/vsts-trigger)
>2017-02-15T18:09:31.8089402Z ==============================================================================
>2017-02-15T18:09:31.8329415Z Preparing task execution handler.
>2017-02-15T18:09:35.1095108Z Executing the powershell script: D:\a\_tasks\ReleaseTrigger_b2d2e081-c1e0-4daf-b444-c492a02e47f8\0.1.1\ReleaseTrigger.ps1
>2017-02-15T18:09:35.3872905Z ReleaseDefinitionName= R2
>2017-02-15T18:09:35.3872905Z 
>2017-02-15T18:09:35.3872905Z 
>2017-02-15T18:09:35.3882919Z TeamProject= TP
>2017-02-15T18:09:35.3882919Z 
>2017-02-15T18:09:35.3882919Z 
>2017-02-15T18:09:35.4362963Z TfsUri= https://XXXXXX.vsrm.visualstudio.com/
>2017-02-15T18:09:35.4362963Z 
>2017-02-15T18:09:35.4362963Z 
>2017-02-15T18:09:35.4382909Z BuildDefinitionId= 150
>2017-02-15T18:09:35.4382909Z 
>2017-02-15T18:09:35.4382909Z 
>2017-02-15T18:09:35.4382909Z BuildDefinitionName= A1
>2017-02-15T18:09:35.4382909Z 
>2017-02-15T18:09:35.4382909Z 
>2017-02-15T18:09:35.4392910Z BuildId= 5416
>2017-02-15T18:09:35.4392910Z 
>2017-02-15T18:09:35.4392910Z 
>2017-02-15T18:09:40.4052951Z url= https://XXXXXX.vsrm.visualstudio.com/TP/_apis/release/definitions?$expand=artifacts&api-version=3.0-preview.1
>2017-02-15T18:09:40.4052951Z 
>2017-02-15T18:09:40.4052951Z 
>2017-02-15T18:09:41.7545625Z Get artifacts versions
>2017-02-15T18:09:41.7545625Z 
>2017-02-15T18:09:41.7545625Z 
>2017-02-15T18:09:41.7545625Z url= https://XXXXXX.vsrm.visualstudio.com/TP/_apis/release/artifacts/versions?api-version=3.0-preview.1
>2017-02-15T18:09:41.7545625Z 
>2017-02-15T18:09:41.7545625Z 
>2017-02-15T18:09:41.9134364Z body= {
>2017-02-15T18:09:41.9134364Z     "sourceId":  "69fe2265-92a6-484c-8711-2aa10257a1bd:80",
>2017-02-15T18:09:41.9134364Z     "type":  "Build",
>2017-02-15T18:09:41.9134364Z     "alias":  "A2",
>2017-02-15T18:09:41.9134364Z     "definitionReference":  {
>2017-02-15T18:09:41.9134364Z                                 "defaultVersionBranch":  {
>2017-02-15T18:09:41.9134364Z                                                              "id":  "",
>2017-02-15T18:09:41.9134364Z                                                              "name":  ""
>2017-02-15T18:09:41.9134364Z                                                          },
>2017-02-15T18:09:41.9144368Z                                 "defaultVersionSpecific":  {
>2017-02-15T18:09:41.9144368Z                                                                "id":  "",
>2017-02-15T18:09:41.9144368Z                                                                "name":  ""
>2017-02-15T18:09:41.9144368Z                                                            },
>2017-02-15T18:09:41.9144368Z                                 "defaultVersionTags":  {
>2017-02-15T18:09:41.9144368Z                                                            "id":  "",
>2017-02-15T18:09:41.9144368Z                                                            "name":  ""
>2017-02-15T18:09:41.9144368Z                                                        },
>2017-02-15T18:09:41.9144368Z                                 "defaultVersionType":  {
>2017-02-15T18:09:41.9154365Z                                                            "id":  "latestType",
>2017-02-15T18:09:41.9154365Z                                                            "name":  "Latest"
>2017-02-15T18:09:41.9154365Z                                                        },
>2017-02-15T18:09:41.9154365Z                                 "definition":  {
>2017-02-15T18:09:41.9154365Z                                                    "id":  "80",
>2017-02-15T18:09:41.9154365Z                                                    "name":  "A2"
>2017-02-15T18:09:41.9164605Z                                                },
>2017-02-15T18:09:41.9164605Z                                 "project":  {
>2017-02-15T18:09:41.9164605Z                                                 "id":  "69fe2265-92a6-484c-8711-2aa10257a1bd",
>2017-02-15T18:09:41.9164605Z                                                 "name":  "TP"
>2017-02-15T18:09:41.9164605Z                                             },
>2017-02-15T18:09:41.9164605Z                                 "artifactSourceDefinitionUrl":  {
>2017-02-15T18:09:41.9164605Z                                                                     "id":  "https://XXXXXX.visualstudio.com/_permalink/_build/index?collectionId=bbdf648e-bdd3-4c5d-8450-835c543bf225\u0026projectId=69fe2265-92a6-484c-8711-2aa10257a1bd\u0026definitionId=80",
>2017-02-15T18:09:41.9174386Z                                                                     "name":  ""
>2017-02-15T18:09:41.9174386Z                                                                 }
>2017-02-15T18:09:41.9174386Z                             }
>2017-02-15T18:09:41.9174386Z }
>2017-02-15T18:09:41.9174386Z 
>2017-02-15T18:09:41.9174386Z 
>2017-02-15T18:09:42.0677181Z ##[error]System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find artifact versions.
>2017-02-15T18:09:42.0677181Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
>2017-02-15T18:09:42.0677181Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
>2017-02-15T18:09:42.0677181Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
>2017-02-15T18:09:42.0677181Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
>2017-02-15T18:09:42.0677181Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
>2017-02-15T18:09:42.0677181Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
>2017-02-15T18:09:42.0816088Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.

**Comment by gokusupa** [comment]
+1
